### ISSUE TITLE
[Feature Request] Some enums are missing in v7

### ISSUE THREAD

**Issue by smallufo** [line/line-bot-sdk-java#1155]
In v6 , there are some pre-defined enums, such as [FontSize](https://github.com/tokuhirom/line-bot-sdk-java/blob/33a7eb4982fc3559b2c3b64b0af2363260b43397/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/unit/FlexFontSize.java#L26),  [ImageAspectRatio](https://github.com/tokuhirom/line-bot-sdk-java/blob/33a7eb4982fc3559b2c3b64b0af2363260b43397/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/component/Image.java#L80),  [RichMenuSize](https://github.com/tokuhirom/line-bot-sdk-java/blob/33a7eb4982fc3559b2c3b64b0af2363260b43397/line-bot-model/src/main/java/com/linecorp/bot/model/richmenu/RichMenuSize.java#L25-L27) , [ImageSize](https://github.com/tokuhirom/line-bot-sdk-java/blob/33a7eb4982fc3559b2c3b64b0af2363260b43397/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/component/Image.java#L51-L73C9) ...  and type-safety methods.
These enums are missing in v7 , is this intentional ?

I still prefer `.size(Image.ImageSize.FULL_WIDTH)`  instead of `.size("full")`

**Comment by Yang-33** [comment]
Hi, I'm working on this. Thank you for your valuable issue.

Currently, almost all code in this repository is based on https://github.com/line/line-openapi.
As I checked this issue, I think FlexFontSize and FlexImageSize can be provided in this repository because they are just undefined unintentionally.
However we don't have plan to provide ImageAspectRatio and RichMenuSize in line-openapi. It's just added manually in this repository, and document(https://developers.line.biz/en/reference/messaging-api/#rich-menu-object) doesn't provide these enum officially.

Thus if you wish to restore them(FlexFontSize and FlexImageSize), you can redefine them in this repository (however, this is not easy to maintain. We will no longer manually add enum codes I guess), or alternatively, please redefine it again in your application.

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-java/pull/1204 will provide some keywords for template message and flex message.
And https://github.com/line/line-bot-sdk-java/pull/1202 will provide a way to convert these keywords into string value.
