### ISSUE TITLE
@LineMessageHandler Not Work for [Line Bot Spring Boot] ver 1.20.0

### ISSUE THREAD

**Issue by LittleYenMin** [line/line-bot-sdk-java#256]
My Spring Boot version 2.0.2.RELEASE and for now i use Line Bot Spring Boot ver 1.19.0

I try to update package [Line Bot Spring Boot] to ver 1.20.0

the annotation @LineMessageHandler and @EventMapping was not found

eclipse warning: 
The import com.linecorp.bot.spring.boot.annotation.EventMapping cannot be resolved
The import com.linecorp.bot.spring.boot.annotation.LineMessageHandler cannot be resolved

**Comment by tokuhirom** [comment]
@kazuki-ma is there any opinions?

**Comment by kazuki-ma** [comment]
@LittleYenMin thank you for your reporting.
Umm.. Let me check....

Could you give me the code to reproduce?

**Comment by LittleYenMin** [comment]
@kazuki-ma 
i don't know how to give u the code than i put it on my github

pls access this link
https://github.com/LittleYenMin/SpringLineBotSampleCode

**Comment by kazuki-ma** [comment]
@LittleYenMin 

Thank you. I checked your repository.

I think the are two issues.

1. you don't need create your own `LineBotProperties`. Just set properties into `application.(yml|properties)`
2. If you will use `line.bot.channelTokenSupplyMode=SUPPLIER`, you should remove `line.bot.channelSecret={channelSecret}`. `line.bot.channelSecret` is the property key for fixed channel token.

After changing those 2 point & minor modifications, I got following logs.

```
2018-08-16 14:15:05.024  INFO 2746 --- [           main] c.l.b.s.b.s.LineMessageHandlerSupport    : Registered LINE Messaging API event handler: count = 1
2018-08-16 14:15:05.025  INFO 2746 --- [           main] c.l.b.s.b.s.LineMessageHandlerSupport    : Mapped "[MessageEvent<TextMessageContent>]" onto public void com.hpifive.line.bcs.webhook.controller.WebhookController.handlerTextMessageEvent(com.linecorp.bot.model.event.MessageEvent<com.linecorp.bot.model.event.message.TextMessageContent>)

...

83298 [http-nio-8080-exec-5] INFO  com.hpifive.line.bcs.webhook.controller.WebhookController  - TextMessage ReceivedMessageEvent(replyToken=8a5a34e1a3494c0189f1e8113f749196, source=UserSource(userId=Ue87f273e325cd42ad2dd65946347f07f), message=TextMessageContent(id=8426333343794, text=test), timestamp=2018-08-16T05:22:30.480Z)
```

Other minor findings
=======
* LINE Bot Spring Boot using Slf4j as logging framework. How about using `private static org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(WebhookController.class);` instead of `log4j`?

**Comment by LittleYenMin** [comment]
**Problem solve**
@kazuki-ma Thanks for you advice

I think i found problem
it's my maven package download fail ...
i redownload and everything worked fine ...
thanks alot
