### ISSUE TITLE
Where I can get the group ID ?

### ISSUE THREAD

**Issue by kiennatibula** [line/line-bot-sdk-java#457]
I plan to create a system that will send a cleaning schedule to my staff . And I need the group id to send a message

**Comment by tkgauri** [comment]
It is returned in the Join event 
https://developers.line.biz/en/reference/messaging-api/#join-event

**Comment by kiennatibula** [comment]
@tkgauri thank you for your reply. 
And sorry for my English.
 I am new in LINE SDK . I want to use the push message https://developers.line.biz/en/reference/messaging-api/#send-push-message api to send a message to my group every day but I have stock for 2 days searching about getting the "to" value my opinion that is the groupID . I already in the group I want to get my group ID to test the API. Can you please teach the exact logic. Thanks :)

**Comment by kazuki-ma** [comment]
We don't provide listing api of joined groups now.

For fixed groups, you collect group id first and set those values as your configuration (like hardcoding).
Otherwise, you stores group id to your database from JoinEvent (or other webhook source).

Notes: You can get `gorupId` from [Source](https://sourcegraph.com/github.com/line/line-bot-sdk-java@master/-/blob/line-bot-model/src/main/java/com/linecorp/bot/model/event/source/Source.java) via `getSenderId`.
Optionally you can cast the instance to [GroupSource\.java \- line/line\-bot\-sdk\-java \- Sourcegraph](https://sourcegraph.com/github.com/line/line-bot-sdk-java@a2b6d5366ebf4809c009270f6b27c5161709e4a4/-/blob/line-bot-model/src/main/java/com/linecorp/bot/model/event/source/GroupSource.java#L27:14).

**Comment by kiennatibula** [comment]
Thank you so much @kazuki-ma . I am sorry my mistake . I use php, is it same process ?

**Comment by kiennatibula** [comment]
@kazuki-ma do you have a documentation link for getting the group id in a fixed group. Because I already in the group I only need to get the group ID . to use it in API .

**Comment by kazuki-ma** [comment]
@kiennatibula Are you using bot-sdk-php?

SDK's repo is here https://github.com/line/line-bot-sdk-php.
And gorupId is also supported.
https://github.com/line/line-bot-sdk-php/search?q=groupId&unscoped_q=groupId

> do you have a documentation link for getting the group id in a fixed group.
The meaning of `fixed` is that you have only group name?
Sorry, there are no API provided to get ID from groupName.

**Comment by kazuki-ma** [comment]
@kiennatibula  Now, let me close this issue.
If you have further questions please re-open it. Thank you!

**Comment by Zulkiflimok** [comment]
group = client.getGroupIdsJoined()
