### ISSUE TITLE
GroupSource.userId?

### ISSUE THREAD

**Issue by tokuhirom** [line/line-bot-sdk-java#57]
It's not documented on devdocs

**Comment by ivan98** [comment]
Hi @tokuhirom 

This looks like #40 (@timgshi) where it will enable Bot to know the sender of message in group/room chat. This is important in my application, where Bot will react differently to the same message in group/room chat, depending on who said it. This is because different users have different privilege levels in my application.

Is this a upcoming feature? Will it propagate to the Python SDK?

**Comment by tokuhirom** [comment]
Sorry, it's unvailable now...

**Comment by yusukeoshiro** [comment]
I am with @ivan98 on this.
What is the point of group conversation if you can't identify the speaker by the user id?

**Comment by jar555** [comment]
Will it become available anytime soon?

**Comment by tokuhirom** [comment]
Sorry, we can't provide any information for now.

**Comment by kazuki-ma** [comment]
Let me close the issue. Please reopen if you have remaining problems.

**Comment by kelvinhalim13** [comment]
yeah im agree with @ivan98, right now im stuck in my BOT to send different message or reaction in group/room chat, i had mad database for a simple "Game" which it can be play in Room / Group Chat, Hope it will be available in future

**Comment by pulungrwo** [comment]
how to setting for view last seen in group line?
