### ISSUE TITLE
[Feature Request] Please make all Response classes Serializable

### ISSUE THREAD

**Issue by smallufo** [line/line-bot-sdk-java#603]
## Feature Request
Please make all Response classes implementing java.io.Serializable. It will help us caching the result object.

**Comment by imasahiro** [comment]
Basically, it is not good idea to make a class serializable due to several reasons (e.g. hard to update the classes, security risk, etc., or you can check "Effective Java" to understand dangers of serialization). Instead, I would like suggest you to make your own response class model (without unnecessary fields) to cache the responses.
